[package]
name = "cat-paw-cat-management"
version = "0.1.0"
description = "猫爪猫咪管理后台"
authors = ["Maozhua"]
edition = "2021"

[lib]
name = "cat_paw_cat_management_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
rusqlite = { version = "0.32", features = ["bundled"] }
base64 = "0.22"
